### ISSUE TITLE
When executing 'run', prompt 'sh: 1: xdg user dir: not found'

### ISSUE THREAD

**Issue by 13120123180** [Auhrus/theisle-evrima-docker-server#3]
Hi Augrus,

Now, I am using your image to build my game server
When I reached the final step and started the container using the 'run' command, an error occurred
`Success! App '412680' already up to date.`
`***Starting The Isle Server`
`Shutdown handler: initialize.`
`5.4.3-0+UE5 1012 0`
`Disabling core dumps.`
`sh: 1: xdg-user-dir: not found`
`Failed to find symbol file, expected location:
"/home/steam/Steam/steamapps/common/The Isle Dedicated Server/TheIsle/Binaries/Linux/TheIsleServer-Linux-Shipping.sym"`
`Engine crash handling finished; re-raising signal 0 for the default handler. Good bye. `

The error message 'sh: 1: xdg user dir: not found' seems to indicate that I need to install 'xdg user dir', but I do not have root privileges in the container
Have you encountered this situation before? It looks like the program is trying to call the monitor or GPU, but my host doesn't have these, it's just a regular server
The command I use to start the container is like this:
`docker run -itd --name theisleevrima --net=host --restart=always -v /mnt/theisleevrima:"/home/steam/Steam/steamapps/common/The Isle Dedicated Server" -e updateonstart=true -e steambranch="evrima" ghcr.io/auhrus/theisleevrima:latest`

Thanks and best wishes to you

**Comment by 13120123180** [comment]
Just now, I compared two identical devices and found that this issue only occurs in the latest version of The Isle, which was updated on August 6th

When I run the old version of the isle,It can run normally
When I use Docker to run the latest version of The Isle, I got `sh: 1: xdg-user-dir: not found`
When I run the latest version of The Isle on the host without Docker, I got `Failed to find symbol file, expected location:
"/mnt/theisleevrima/TheIsle/Binaries/Linux/TheIsleServer-Linux-Shipping.sym"`

So, this seems to be a bug caused by game updates
I also left a message for game developers

If you have any updates, thank you for letting me know as soon as possible

**Comment by 13120123180** [comment]
Hi Augrus,
Today, I brought the latest situation.
After updating to the latest version 203, although the error message has not changed, I am now able to find my server in the game interface, which is a great improvement

However, after multiple attempts, I was unable to connect to this server and the game interface kept showing "DATA ACQUISITION FAILED"
That's a line of bright red text in the center of the screen, you must be familiar with it

Now, I am trying to solve the problem of players being unable to enter
The error in the log seems to have no impact on the operation of the service, so I have decided not to pay attention to it anymore

**Comment by 13120123180** [comment]
hi bro
My problem has been resolved
The solution is to set the rcon port and queuing port to 8888 and 10000 respectively in Game.ini
No other modifications were made, it can now run normally

**Comment by Auhrus** [comment]
Hi @13120123180,

I apologize for the late response. I have also been working for a few days to find out why I get the message "DATA ACQUISITION FAILED". 
Thank you for sharing your solution here.🙂 That seems to have been the problem for me too. 🎉

Regarding the "xdg-user-dir".
I will update ⏫ the [Dockerfile](https://github.com/Auhrus/theisle-evrima-docker-server/blob/ae8a1310998593b661b94a8f42173b863277ec06/Dockerfile) today and edit the documentation + the [basic-configs](https://github.com/Auhrus/theisle-evrima-docker-server/tree/main/basic-configs) as well.

**Comment by Auhrus** [comment]
@13120123180 again,

the image has now been updated (2357c544daa90fc062bced9300540ca608987bb4) and should work. I have also found out that if you set the "bQueueEnabled" setting to false, port 1000 is not required. I have added a point for the "DATA ACQUISITION FAILED" error in the README under [IMPORTANT‼️](https://github.com/Auhrus/theisle-evrima-docker-server#important%EF%B8%8F). 🙂

**Comment by 13120123180** [comment]
Hi, my friend, I have encountered a new problem now,
After running my service, I am unable to connect to the rcon port through any client
Whether it's downloading various client software from the internet or writing code to connect, the results are always failures

It is worth mentioning that when I started the service using your images, I used the parameter '-- net=host' instead of configuring each port
I am trying to solve this problem by mapping each port separately
Before I receive the results, if you think of any other possibilities, please let me know. Thank you

**Comment by Auhrus** [comment]
Hi again,

I have checked this for myself and the RCON works perfectly with this tool here ([The-Isle-Evrima-Server-Tools](https://github.com/modernham/The-Isle-Evrima-Server-Tools/releases)). Then you have to check if the RCON port you have set in the Game.ini is enabled for TCP and UDP.

**Comment by 13120123180** [comment]
I tried on the same computer and other computers separately, and found that following the instructions for the SourceRCON protocol on the SteamCMD website always failed to connect
Finally, I found a custom connection tool for evrima on Github, and now I have successfully connected
I am currently reading the source code of this open-source project and trying to discover how the Rcon protocol of 'The Isle' differs from other games, resulting in only customized connection tools being able to connect correctly
The information provided in the official documents is not enough for me. I cannot see what custom modifications the game developers have made to the Rcon protocol, so I can only reverse engineer it based on the code of other players

**Comment by 13120123180** [comment]
Now, what I want is not the Rcon connection tool
I want to develop my own game management interface based on Rcon connection, which can browse player information on the server and perform management operations on the webpage
This requires me to be able to establish a connection with Evrima Rcon service using code
But it seems that The Isle's Rcon protocol has undergone some modifications, which makes it impossible for me to connect to it using all common Rcon frameworks
I found from the code of the connection tools customized by other players that they seem to have not used any open-source libraries for connection. They all need to write a large amount of underlying code themselves to connect to Rcon and format message content
I will solve this problem, but it will take some time to learn

**Comment by 13120123180** [comment]
I have completed this project, but based on the interfaces currently provided by RCON, they cannot fully support all of my requirements, such as:
I hope to send a welcome announcement to every player when they go online, so how can I keep track of them in real time? Can we just keep getting the player list and checking its data changes?
I hope to execute a player at any time. How should I proceed? Perhaps by kicking out the server and deleting its archived data?
I hope to be able to modify the player's save data, such as changing their body size or hunger value, or even moving them to a certain position at will. I have no idea about this.

Another small issue is about the content of Gamainini. I found that in the latest version of the game, players cannot be born in the same location after dying in each area, but I have seen a different phenomenon on other servers. I couldn't find any relevant configurations in Gamainini, do you know?

**Comment by Auhrus** [comment]
So I don't know what else you can set in the Game.ini. Maybe you can write to the developers again like you did with the error above, maybe they can help you.

**Comment by jk0928-pro** [comment]
> Hi again,
> 
> I have checked this for myself and the RCON works perfectly with this tool here ([The-Isle-Evrima-Server-Tools](https://github.com/modernham/The-Isle-Evrima-Server-Tools/releases)). Then you have to check if the RCON port you have set in the Game.ini is enabled for TCP and UDP.

how can i check if the TCP and UDP its enabled in game.ini cuz i just set QueuePort=10000 and RconPort=8888 and im still getting  "DATA ACQUISITION FAILED"

**Comment by 13120123180** [comment]
> > Hi again,   你好再次,
> > I have checked this for myself and the RCON works perfectly with this tool here ([The-Isle-Evrima-Server-Tools](https://github.com/modernham/The-Isle-Evrima-Server-Tools/releases)). Then you have to check if the RCON port you have set in the Game.ini is enabled for TCP and UDP.我已经为自己检查过了，RCON可以完美地使用这个工具（the - isle - evrima - server - tools）。然后你必须检查你在Game.ini中设置的RCON端口是否为TCP和UDP启用。
> 
> how can i check if the TCP and UDP its enabled in game.ini cuz i just set QueuePort=10000 and RconPort=8888 and im still getting "DATA ACQUISITION FAILED"我如何检查TCP和UDP是否在game.ini中启用，因为我刚刚设置QueuePort=10000和RconPort=8888，我仍然得到“数据采集失败”

You need to add all the ports you need when running the container, just like this：

`docker run --name CONTAINER_NAME -p 8888 :8888 /tcp -p 10000 :10000 /tcp -p 7777:7777/udp -v VOLUME_NAME:"/home/steam/Steam/steamapps/common/The Isle Dedicated Server" ghcr.io/auhrus/theisleevrima:latest`

At the same time, you need to ensure that your queue port is open to the Internet
You can use another computer to try using “telnet+your public IP+your public Port” to test if your port can be accessed, just like this：
`telnet 123.123.123.123 10000`

I hope it can help you

**Comment by jk0928-pro** [comment]
> > > Hi again,   你好再次,
> > > I have checked this for myself and the RCON works perfectly with this tool here ([The-Isle-Evrima-Server-Tools](https://github.com/modernham/The-Isle-Evrima-Server-Tools/releases)). Then you have to check if the RCON port you have set in the Game.ini is enabled for TCP and UDP.我已经为自己检查过了，RCON可以完美地使用这个工具（the - isle - evrima - server - tools）。然后你必须检查你在Game.ini中设置的RCON端口是否为TCP和UDP启用。
> > 
> > 
> > how can i check if the TCP and UDP its enabled in game.ini cuz i just set QueuePort=10000 and RconPort=8888 and im still getting "DATA ACQUISITION FAILED"我如何检查TCP和UDP是否在game.ini中启用，因为我刚刚设置QueuePort=10000和RconPort=8888，我仍然得到“数据采集失败”
> 
> You need to add all the ports you need when running the container, just like this：
> 
> `docker run --name CONTAINER_NAME -p 8888 :8888 /tcp -p 10000 :10000 /tcp -p 7777:7777/udp -v VOLUME_NAME:"/home/steam/Steam/steamapps/common/The Isle Dedicated Server" ghcr.io/auhrus/theisleevrima:latest`
> 
> At the same time, you need to ensure that your queue port is open to the Internet You can use another computer to try using “telnet+your public IP+your public Port” to test if your port can be accessed, just like this： `telnet 123.123.123.123 10000`
> 
> I hope it can help you

do i have to create a new file or add all of that in game.ini im sorry i dont know how to set up that thing

**Comment by 13120123180** [comment]
@Auhrus My good brother, please help him. My English level is limited and I didn't fully understand his meaning.
